Добавил паттерн фабрика
Velier12/java-patterns pull request #1
Opened 2024-06-11 12:32 UTC by Velier12

2024-06-11 14:02 UTC, gobaz095 requested changes
А также читаем про https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13
И стараемся писать коммиты по шаблону

2024-06-11 14:02 UTC, gobaz095 commented on .idea/checkstyleidea-libs/readme.txt
Давай все же README.md

2024-06-11 14:02 UTC, gobaz095 commented on src/main/java/patterns/factory/Employee.java
Тоже хочу javadoc

2024-06-12 00:46 UTC, Velier12 commented
Можно сливать ?

2024-06-13 08:15 UTC, gobaz095 approved these changes
Можно сливать

2024-06-13 08:38 UTC, merged